#!/bin/bash

set -eu

env_file="$(dirname "${BASH_SOURCE[0]}")/.env"

if [ -f "${env_file}" ]
then
  export $(grep -v '^#' "${env_file}")
fi

exec aws --endpoint-url="http://${LOCALSTACK_HOSTNAME}:${LOCALSTACK_PORT}" "${@}"
