services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "${LOCALSTACK_IP}:${LOCALSTACK_PORT}:${LOCALSTACK_PORT}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
