require 'dotenv'

task default: :test

desc 'Load .env file from parent directory'
task :dotenv do
  Dotenv.load(File.join('..', '.env'))
end

desc 'Test Lambda'
task test: :dotenv do
  ruby 'lambda_function.rb'
end

desc 'Package Lambda as ZIP'
task :package do
  sh 'rm -f lambda_function_payload.zip'
  sh 'zip lambda_function_payload.zip lambda_function.rb'
end
