name: Terraform common steps
description: Setup Terraform and get dependencies

runs:
  using: composite
  steps:
    - uses: isbang/compose-action@v1.0.0
      with:
        compose-file: compose.yaml
    - name: Read .terraform-version
      id: terraform_version
      uses: juliangruber/read-file-action@v1
      with:
        path: .terraform-version
        trim: true
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ steps.terraform_version.outputs.content }}
    - uses: actions/download-artifact@v2
      with:
        name: bucket-list-lambda
        path: lambda/bucket-list/gen/
