name: Terraform common steps
description: Setup Terraform and get dependencies

runs:
  using: composite
  steps:
    - uses: isbang/compose-action@v1.0.0
      with:
        compose-file: compose.yaml
    - name: Read .terraform-version
      id: terraform_version
      uses: juliangruber/read-file-action@v1
      with:
        path: .terraform-version
        trim: true
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ steps.terraform_version.outputs.content }}
    - name: Setup Terrafile
      shell: bash
      run: wget https://github.com/coretech/terrafile/releases/download/v0.6/terrafile_0.6_Linux_x86_64.tar.gz -O- | tar xz
    - name: Install Terraform modules from Terrafile
      shell: bash
      run: ./terrafile
    - uses: actions/download-artifact@v2
      with:
        name: bucket-list-lambda
        path: lambda/bucket-list/gen/
